# typed: false
# frozen_string_literal: true

# Auto-generated by pipemason's release workflow. Do not edit by hand —
# changes will be overwritten on the next release.
class Pipemason < Formula
  desc "Local runner for the pipemason development pipeline"
  homepage "https://pipemason.com"
  version "0.3.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.0/pipemason-darwin-arm64"
      sha256 "36052ceba6b56f58b5ffe745c20b5a7ae0beec4d83b00d7e87efde728e6740f9"
    end
    on_intel do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.0/pipemason-darwin-x64"
      sha256 "7ef8ed6c032569fc68cc1430c13a3dd2d1708249b13abb8eb34aa27e2366b9c6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.0/pipemason-linux-arm64"
      sha256 "cefb804106085a48a137115562d7e45fe931e3a791e2756abcb9a0fec61de64e"
    end
    on_intel do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.0/pipemason-linux-x64"
      sha256 "8f72a6040f8654a6356bd8d4c5c8dfaefadb3c253320171d0596545e69a95cb8"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x64"
    bin.install "pipemason-#{os}-#{arch}" => "pipemason"
  end

  def caveats
    <<~CAVEATS
      You're installed. Three steps to your first run:

        1. Create an account (14-day free trial, no charge until day 15):
             https://pipemason.com

        2. Pair this machine to your account:
             pipemason login

        3. From inside any git repo, kick off a run:
             pipemason start "add a /version endpoint"

           Or use the interactive walkthrough (recommended for first-timers):
             pipemason setup

      Docs: https://pipemason.com/onboarding
      Dashboard: https://pipemason.com/dashboard
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipemason --version")
  end
end
