# typed: false
# frozen_string_literal: true

# Auto-generated by pipemason's release workflow. Do not edit by hand —
# changes will be overwritten on the next release.
class Pipemason < Formula
  desc "Local runner for the pipemason development pipeline"
  homepage "https://pipemason.com"
  version "0.3.1"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.1/pipemason-darwin-arm64"
      sha256 "ef8bccbdb9ee3203206755b4715e1dc3644fcf4d578b5b6f4734e8f930650b9a"
    end
    on_intel do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.1/pipemason-darwin-x64"
      sha256 "321b1150b0411973576b11900cd944a86c17d24a24cf16e6a1beb762caed1c8c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.1/pipemason-linux-arm64"
      sha256 "e9b8cf1de3eac9ba8b41912a8d8edccbf5a94c050aace398746d2bcf9bbaed60"
    end
    on_intel do
      url "https://github.com/CrashBytes/pipemason-binaries/releases/download/v0.3.1/pipemason-linux-x64"
      sha256 "637ca54195c4e2d3a769d40b02ca29f7594cf2835f8fef52e3c6f23976c967ba"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x64"
    bin.install "pipemason-#{os}-#{arch}" => "pipemason"
  end

  def caveats
    <<~CAVEATS
      You're installed. Three steps to your first run:

        1. Create an account (14-day free trial, no charge until day 15):
             https://pipemason.com

        2. Pair this machine to your account:
             pipemason login

        3. From inside any git repo, kick off a run:
             pipemason start "add a /version endpoint"

           Or use the interactive walkthrough (recommended for first-timers):
             pipemason setup

      Docs: https://pipemason.com/onboarding
      Dashboard: https://pipemason.com/dashboard
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipemason --version")
  end
end
