# typed: false
# frozen_string_literal: true

# Auto-generated by pipemason's release workflow. Do not edit by hand —
# changes will be overwritten on the next release.
class Pipemason < Formula
  desc "Local runner for the pipemason development pipeline"
  homepage "https://pipemason.com"
  version "0.1.11"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/CrashBytes/pipemason/releases/download/v0.1.11/pipemason-darwin-arm64"
      sha256 "7f29382c542c097f2f1627fc7cf882cb7450cab89c312c2884057b00f785cf9d"
    end
    on_intel do
      url "https://github.com/CrashBytes/pipemason/releases/download/v0.1.11/pipemason-darwin-x64"
      sha256 "501690727f2fc7d8410f68520deaf3ca9a9d26c54ccf6ab8ea2f853c8ceb3fa5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/CrashBytes/pipemason/releases/download/v0.1.11/pipemason-linux-arm64"
      sha256 "c8412c22a908490cc9ba94391ce43e059d23c104a9218cef4bb205e725246b7f"
    end
    on_intel do
      url "https://github.com/CrashBytes/pipemason/releases/download/v0.1.11/pipemason-linux-x64"
      sha256 "1c41878cc9d39917e46dfe687f72e23008d0b64bb00ad9d4b2eaf42f4bbf0ff2"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x64"
    bin.install "pipemason-#{os}-#{arch}" => "pipemason"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipemason --version")
  end
end
